export const THEME_CONFIG = {
    // token: {
    //   colorText: '#021815',
    //   colorError: '#B41825',
    //   colorWarning: '#F28118',
    //   colorSuccess: '#1A8E58',
    //   colorPrimary: '#1A8A8E',
    //   colorInfo: 'var(--secondary)',
    //   colorSuccessBg: 'var(--bg-successful)',
    //   colorSuccessBorder: 'var(--color-border-successful)',
    //   colorWarningBg: 'var(--bg-warning)',
    //   colorWarningBorder: 'var(--color-border-warning)',
    //   colorErrorBg: 'var(--bg-error)',
    //   colorErrorBorder: 'var(--color-border-error)',
    // },
    components: {
        // Button: {
        //     defaultHoverBg: '#3052bd',
        //
        // },
        // Button: {
        //     primaryColor: 'var(--color-white-[1])',
        //     defaultColor: 'var(--color-green-2)',
        //     defaultBg: 'var(--button-secondary)',
        //     defaultBorderColor: 'var(--color-green-2)',
        //     defaultHoverBg: 'var(--color-green-7)',
        //     defaultHoverColor: 'var(--button-hover)',
        //     defaultHoverBorderColor: 'var(--button-hover)',
        //     defaultActiveBg: 'var(--secondary-disabled)',
        //     defaultActiveColor: 'var(--color-green-4)',
        //     defaultActiveBorderColor: 'var(--color-green-2)',
        //     textTextColor: 'var(--color-green-2)',
        //     textTextHoverColor: 'var(--button-hover)',
        //     textTextActiveColor: 'var(--color-green-4)',
        //     colorPrimary: 'var(--color-green-2)',
        //     colorPrimaryHover: 'var(--button-hover)',
        //     colorPrimaryActive: 'var(--color-green-4)',
        //     borderRadius: 10,
        //     colorBgContainerDisabled: 'var(--color-white-3)',
        //     colorLink: 'var(--color-green-2)',
        //     colorLinkActive: 'var(--color-green-4)',
        //     colorLinkHover: 'var(--button-hover)',
        //     colorTextDisabled: 'var(--color-gray-6)',
        //     controlHeight: 40,
        //     controlHeightSM: 32,
        //     borderRadiusSM: 10,
        //   },
        //   Checkbox: {
        //     controlInteractiveSize: 20,
        //     colorBorder: 'var(--color-green-2)',
        //     colorPrimary: 'var(--color-green-2)',
        //     colorPrimaryHover: 'var(--color-green-3)',
        //   },
        Button: {
            colorPrimary: '#1963aa',
            colorPrimaryHover: '#144d7a',
            colorPrimaryActive: '#0f3b5c',
            colorTextLightSolid: '#ffffff',

            fontWeight: 600,
            fontSize: 16,
            controlHeight: 48,
            paddingInline: 20,
            borderRadius: 8,
        },
        Radio: {
            wireframe: true,
            colorBorder: '#1963aa',
            colorPrimary: '#1963aa',
            colorPrimaryHover: '#144d7a',
            dotColorDisabled: '#1963aa',
            radioSize: 20,
            dotSize: 12,
            borderRadius: 80,
            padding: 4,
        },

        //   Collapse: {
        //     borderRadiusLG: 0,
        //   },
        //   Switch: {
        //     trackMinWidth: 30,
        //     trackHeight: 16,
        //     handleSize: 12,
        //     colorPrimary: 'var(--color-green-2)',
        //     colorPrimaryHover: 'var(--color-green-3)',
        //   },
        Input: {
            controlHeight: 48,
            borderRadius: 8,
            paddingInline: 12,
            color: '#868696',
            fontWeight: 400,
            fontSize: 16,
            lineHeight: 1.25,
            colorBorder: '#e1e2e7',
            colorBgContainer: '#f3f3f3',
            colorText: '#344153',
            colorBorderHover: '#a0a0a0',
            colorBorderActive: '#1890ff',
            boxShadow: 'none',
            boxShadowError: 'none',
            addonBg: 'transparent',
        },

        //   InputNumber: {
        //     controlHeight: 40,
        //     activeBorderColor: 'var(--button-active)',
        //     hoverBorderColor: 'var(--color-gray-6)',
        //     activeShadow: 'none',
        //     errorActiveShadow: 'none',
        //     borderRadius: 10,
        //     addonBg: 'transparent',
        //   },
        //   DatePicker: {
        //     activeShadow: 'none',
        //     activeBorderColor: 'var(--button-active)',
        //     hoverBorderColor: 'var(--color-gray-6)',
        //     colorPrimaryHover: 'var(--color-gray-6)',
        //     controlHeight: 40,
        //     borderRadius: 10,
        //   },
        //   Form: {
        //     labelColor: 'var(--color-primary)',
        //     labelFontSize: 14,
        //   },
        //   Dropdown: {
        //     controlItemBgHover: 'var(--dropdown-hover)',
        //   },
        //   Select: {
        //     optionSelectedBg: 'var(--dropdown-hover)',
        //     optionActiveBg: 'var(--dropdown-hover)',
        //     optionSelectedFontWeight: '400',
        //   },
        //   Tabs: { colorPrimary: 'var(--color-white-[1])', lineWidth: 0 },
        Form: {
            labelColor: '#868696',
            labelFontSize: 14,
            labelLineHeight: 1.43,
            labelFontWeight: 400,
            labelRequiredMarkColor: '#B41825',
            labelPaddingInlineEnd: 8,

        },

        Breadcrumb: {
            iconFontSize: 16,
            fontSize: 16,
            itemColor: '#2b2d34',
            linkColor: '#2b2d34',
            linkHoverColor: '#2b2d34',
            lastItemColor: '#868696',
            separatorColor: '#2b2d34',
            colorBgHover: 'transparent',
        }

        //   Tag: {
        //     colorInfo: 'var(--info)',
        //     colorInfoBg: 'var(--bg-ifo-light-blue)',
        //     colorInfoBorder: 'var(--color-border-info)',
        //     defaultBg: 'var(--color-gray-4)',
        //   },
        //   Tooltip: {
        //     colorBgSpotlight: 'var(--action-panel)',
        //     colorTextLightSolid: 'var(--secondary)',
        //   },
    },
};
